(()=>{'use strict';
const c=document.getElementById('waterGL'),s=document.getElementById('spray'),ctx=s.getContext('2d'),bg=document.getElementById('background'),amt=document.getElementById('amount'),txt=document.getElementById('amountText'),file=document.getElementById('file'),reset=document.getElementById('reset');
const gl=c.getContext('webgl',{alpha:false,antialias:false});if(!gl){alert('このブラウザではWebGLが使えません。');return}
let W=1,H=1,D=1,iW=1,iH=1,tex,ready=false,url=null,last=performance.now(),imp=[],pts=[];txt.textContent=amt.value+'%';amt.oninput=()=>txt.textContent=amt.value+'%';
const V='attribute vec2 p;varying vec2 v;void main(){v=p*.5+.5;gl_Position=vec4(p,0.,1.);}';
const F=`precision highp float;varying vec2 v;uniform sampler2D t;uniform vec2 res,imgRes;uniform float time,amount;uniform vec4 impacts[10];uniform int count;
float hash(vec2 p){p=fract(p*vec2(123.34,345.45));p+=dot(p,p+34.345);return fract(p.x*p.y);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+vec2(1.,1.)),f.x),f.y);}float fbm(vec2 p){float z=0.,a=.5;for(int i=0;i<5;i++){z+=noise(p)*a;p*=2.;a*=.5;}return z;}
vec2 cover(vec2 u){float va=res.x/res.y,ia=imgRes.x/imgRes.y;if(va>ia){float h=ia/va;u.y=(u.y-.5)*h+.5;}else{float w=va/ia;u.x=(u.x-.5)*w+.5;}return clamp(u,.001,.999);}
float field(vec2 u){float m=0.;for(int i=0;i<10;i++){if(i>=count)break;vec2 q=(u-impacts[i].xy)*vec2(res.x/res.y,1.);float d=length(q),a=impacts[i].z,k=impacts[i].w,r=.045+.36*k;float b=1.-smoothstep(r*.35,r,d),n=fbm(q*24.+float(i)*8.),n2=fbm(q*70.-vec2(0.,a*1.4));m=max(m,b*(.5+.7*n*.6+n2*.15)*k*(1.-smoothstep(.45,1.35,a)));}return clamp(m,0.,1.);}
float height(vec2 u){float h=0.;for(int i=0;i<10;i++){if(i>=count)break;vec2 q=(u-impacts[i].xy)*vec2(res.x/res.y,1.);float d=length(q),a=impacts[i].z,k=impacts[i].w,r=.05+.35*k,b=1.-smoothstep(r*.2,r,d);h+=b*(fbm(q*25.+float(i)*7.)*.75+fbm(q*75.-vec2(0.,a))*.25)*k*(1.-smoothstep(.5,1.4,a));}return h;}
vec3 samp(vec2 u,float b){vec2 e=vec2(1./res.x,1./res.y)*b;vec3 x=texture2D(t,cover(u)).rgb;x+=texture2D(t,cover(u+vec2(e.x,0.))).rgb;x+=texture2D(t,cover(u-vec2(e.x,0.))).rgb;x+=texture2D(t,cover(u+vec2(0.,e.y))).rgb;x+=texture2D(t,cover(u-vec2(0.,e.y))).rgb;return x/5.;}
void main(){vec2 u=v;float wet=field(u),e=vec2(1./res.x,1./res.y)*1.7;float l=height(u-e.xyy),r=height(u+e.xyy),d=height(u-e.yxy),q=height(u+e.yxy);vec2 n=vec2(l-r,d-q)*2.8;vec2 off=n*(.012+.045*amount)*wet;vec3 col=samp(u+off,1.+5.*wet*amount);float micro=fbm(u*95.+time*.025),spark=pow(max(micro-.7,0.),9.)*wet*2.;float edge=clamp(length(n)*5.,0.,1.);col=mix(col,col*vec3(.9,.975,1.035),wet*.18);col+=vec3(.82,.94,1.)*(edge*.2+spark);gl_FragColor=vec4(col,1.);}`;
function sh(t,x){let q=gl.createShader(t);gl.shaderSource(q,x);gl.compileShader(q);if(!gl.getShaderParameter(q,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(q));return q}let p=gl.createProgram();gl.attachShader(p,sh(gl.VERTEX_SHADER,V));gl.attachShader(p,sh(gl.FRAGMENT_SHADER,F));gl.linkProgram(p);gl.useProgram(p);let b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);let ap=gl.getAttribLocation(p,'p');gl.enableVertexAttribArray(ap);gl.vertexAttribPointer(ap,2,gl.FLOAT,false,0,0);let U={t:gl.getUniformLocation(p,'t'),res:gl.getUniformLocation(p,'res'),img:gl.getUniformLocation(p,'imgRes'),time:gl.getUniformLocation(p,'time'),amount:gl.getUniformLocation(p,'amount'),imp:gl.getUniformLocation(p,'impacts'),count:gl.getUniformLocation(p,'count')};tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);
function upload(){if(!bg.complete||!bg.naturalWidth)return;iW=bg.naturalWidth;iH=bg.naturalHeight;gl.bindTexture(gl.TEXTURE_2D,tex);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,bg);ready=true}bg.addEventListener('load',upload);if(bg.complete)upload();
function resize(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,1.5);c.width=s.width=W*D;c.height=s.height=H*D;c.style.width=s.style.width=W+'px';c.style.height=s.style.height=H+'px';ctx.setTransform(D,0,0,D,0,0);gl.viewport(0,0,c.width,c.height)}addEventListener('resize',resize);resize();
function fire(x,y){let k=+amt.value/100,sx=W*.5,sy=H*.27,dx=x-sx,dy=y-sy,L=Math.hypot(dx,dy)||1,ux=dx/L,uy=dy/L;imp.unshift({x:x/W,y:1-y/H,z:0,w:k});if(imp.length>10)imp.pop();for(let i=0,n=70+k*170;i<n;i++){let t=Math.random()*.95,sp=(Math.random()-.5)*(7+k*60)*(t+.2);pts.push({x:sx+dx*t-uy*sp,y:sy+dy*t+ux*sp,vx:ux*(450+Math.random()*500),vy:uy*(450+Math.random()*500),r:.7+Math.random()*(1.8+k*6),life:.12+Math.random()*.7,max:0,a:.25+Math.random()*.7});pts.at(-1).max=pts.at(-1).life}}
document.addEventListener('pointerdown',e=>{if(e.target.closest('.ui'))return;fire(e.clientX,e.clientY)});file.onchange=e=>{let f=e.target.files?.[0];if(!f)return;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(f);bg.onload=upload;bg.src=url};reset.onclick=()=>{imp=[];pts=[]};
function draw(dt){ctx.clearRect(0,0,W,H);for(let i=pts.length-1;i>=0;i--){let x=pts[i];x.life-=dt;if(x.life<=0){pts.splice(i,1);continue}x.x+=x.vx*dt;x.y+=x.vy*dt;x.vx*=.984;x.vy*=.984;let a=Math.max(0,x.life/x.max)*x.a,g=ctx.createRadialGradient(x.x-x.r*.35,x.y-x.r*.35,.1,x.x,x.y,x.r*2.4);g.addColorStop(0,`rgba(255,255,255,${a*.85})`);g.addColorStop(.2,`rgba(225,248,255,${a*.48})`);g.addColorStop(1,'rgba(150,215,240,0)');ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(x.x,x.y,x.r*2.1,x.r,.15,0,Math.PI*2);ctx.fill()}}
function frame(now){let dt=Math.min(.033,(now-last)/1000);last=now;for(let x of imp)x.z+=dt;imp=imp.filter(x=>x.z<1.35);if(ready){let a=new Float32Array(40);imp.forEach((x,i)=>{a[i*4]=x.x;a[i*4+1]=x.y;a[i*4+2]=x.z;a[i*4+3]=x.w});gl.useProgram(p);gl.uniform1f(U.time,now/1000);gl.uniform2f(U.res,c.width,c.height);gl.uniform2f(U.img,iW,iH);gl.uniform1f(U.amount,+amt.value/100);gl.uniform1i(U.count,imp.length);gl.uniform4fv(U.imp,a);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,tex);gl.uniform1i(U.t,0);gl.drawArrays(gl.TRIANGLES,0,6)}draw(dt);requestAnimationFrame(frame)}requestAnimationFrame(frame);
})();
